object BuildDependenciesVersions {
    const val APPCOMPAT = "1.4.2"
    const val MATERIAL = "1.6.1"
    const val CORE_KTX = "1.8.0"
    const val CONSTRAIN_LAYOUT = "2.1.4"
    const val HILT = "2.38.1"
    const val VIEW_PAGER = "1.0.0"
    const val SPLASH_SCREEN= "1.0.0-rc01"
    const val COROUTINE = "1.6.0"
    const val GLIDE = "4.13.2"
    const val FRAGMENT = "1.5.0"
    const val NAVIGATION = "2.5.0"
    const val PAGING = "3.1.1"
    const val ROOM = "2.4.2"
    const val RETROFIT = "2.9.0"
    const val MATERIAL_DIALOG = "3.2.1"
    const val RECYCLER_VIEW = "1.2.1"
    const val LIFECYCLE = "2.5.0"
    const val OKHTTP = "4.10.0"

    const val JUNIT = "4.13.1"
    const val EXT = "1.1.2"
    const val ESPRESSO = "3.3.0"
}
